spring:
  application:
    name: service-b

server:
  port: 8081

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
